language: java
jdk: oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install -DskipTests
  - bash <(curl -s https://codecov.io/bash)

services:
  - postgresql

# before_script:



