language: java
jdk: oraclejdk8

services:
  - postgresql

install: true

cache:
  directories:
  - $HOME/.m2

before_script:
  - psql -U postgres -f src/main/resources/db/schema.sql

script:
  - mvn clean install -Dspring.profiles.active=$SPRING_PROFILE
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)






