spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/methods
    username: methods
    password: methods

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: mdb_data
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true       
    
  http:
    converters:
      preferred-json-mapper: jackson
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Europe/Berlin
    locale: de_DE
    default-property-inclusion: non_null
    serialization-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false
    mapper:
      sort-properties-alphabetically: true
      default-view-inclusion: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
  # file: /var/log/methods/app.log

azure:
  activedirectory:
    client-secret: t8lFHodtiXdZMU0p4P0SpkLVIEfhg8bkt35DLihC3DQ=
    client-id: d08628b7-a0cd-4679-bdd7-f12d92f3cb0f
    active-directory-groups: Editors,EDITOR

server:
  servlet:
    contextPath: /api

management:
  port: 7979
  security:
    enabled: false
  add-application-context-header: false
endpoints:
  actuator:
    enabled: false
  autoconfig:
    enabled: false
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  flyway:
    enabled: false
  liquibase:
    enabled: false
  logfile:
    enabled: false
  mappings:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false
  health:
    sensitive: false

cors:
  allowedOrigins:
  - "http://localhost"
  - "http://localhost:8080"
  - "localhost:8080"
  - "localhost:8081"
  - "localhost"
  - "http://localhost:8081"
  allowedMethods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
  - OPTIONS
  allowedHeaders:
  - Authorization
  - Content-Type
  - X-Flow-ID
  - X-User-ID
  - Accept
  exposedHeaders:
  - X-Flow-ID
  - X-User-ID
  maxAge: 3600
  allowCredentials: true

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/methods

