spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/methodendb
    username: methodendb
    password: methodendb
  metrics:
    export:
      delay-millis: 5000



  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: mdb_data
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true       
    
  http:
    converters:
      preferred-json-mapper: jackson
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Europe/Berlin
    locale: de_DE
    serialization-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false
    
logging:
  file: /var/log/methodendb/app.log
#  level:
#    ROOT: WARN # DEBUG
      
server:
  port: 8080

# Sane configuration with the management endpoints (Actuator)
management:
  port: 7979
  # We don't want security here as we will not expose that port to the outside world anyway
  security:
    enabled: false
  # Let's not disclose we're running on Spring :-)
  add-application-context-header: false
endpoints:
  actuator:
    enabled: false
  autoconfig:
    enabled: false
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  flyway:
    enabled: false
  liquibase:
    enabled: false
  logfile:
    enabled: false
  mappings:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false
  health:
    # Have the full health result even when not authenticated
    sensitive: false

influx:
  host: http://0.0.0.0
  port: 8086

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/methodendb
    username: methodendb
    password: methodendb

influx:
  host: http://influxdb
  port: 8086

