spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/methodendb
    username: methodendb
    password: methodendb
  metrics:
    export:
      delay-millis: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: mdb_data
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true       
    
  http:
    converters:
      preferred-json-mapper: jackson
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Europe/Berlin
    locale: de_DE
    default-property-inclusion: non_null
    serialization-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false
    mapper:
      sort-properties-alphabetically: true
      default-view-inclusion: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    
#logging:
#  file: /var/log/methodendb/app.log
#  level:
#    ROOT: DEBUG #WARN # DEBUG
      
server:
  port: 8080

management:
  port: 7979
  security:
    enabled: false
  add-application-context-header: false
endpoints:
  actuator:
    enabled: false
  autoconfig:
    enabled: false
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  flyway:
    enabled: false
  liquibase:
    enabled: false
  logfile:
    enabled: false
  mappings:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false
  health:
    sensitive: false

influx:
  host: http://0.0.0.0
  port: 8086

security:
  user:
    password: password
  oauth2:
    client:
      clientId: methodendb
      clientSecret: secret
      accessTokenUri: http://0.0.0.0:8888/oauth/token
      userAuthorizationUri: http://0.0.0.0:8888/oauth/authorize
    resource:
      userInfoUri: http://0.0.0.0:8080/user

cors:
  allowedOrigins:
  - "http://localhost"
  - "http://localhost:8080"
  - "localhost:8080"
  - "localhost:8081"
  - "http://localhost:8081"
  allowedMethods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
  - OPTIONS
  allowedHeaders:
  - Authorization
  - Content-Type
  - X-Flow-ID
  - X-User-ID
  exposedHeaders:
  - X-Flow-ID
  maxAge: 3600


---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/methodendb
    username: methodendb
    password: methodendb

influx:
  host: http://influxdb
  port: 8086

